[project]
name = "linkedin-demo"
version = "0.1.0"
description = "LinkedIn Demo MCP Server - A simple demonstration server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.4.1",
]
