name: CI Pipeline

# This workflow can be triggered manually via GitHub UI
on:
  workflow_dispatch:
    inputs:
      python_version:
        description: "Python version to use"
        required: false
        default: "3.12"
        type: choice
        options:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
      run_coverage:
        description: "Generate coverage report"
        required: false
        default: true
        type: boolean

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python_version || '3.12' }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version || '3.12' }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Run CI Pipeline
        run: make ci

      - name: Upload coverage HTML report
        if: ${{ inputs.run_coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: htmlcov/
          retention-days: 30
